pandas: 데이터 분석을 위한 라이브러리, 주로 데이터프레임 생성 및 조작에 사용  
numpy: 수치 계산 및 배열/행렬 처리를 위한 라이브러리  
matplotlib.pyplot: 데이터 시각화를 위한 라이브러리, 그래프(라인, 바, 히스토그램 등) 작성에 사용  
train_test_split: 데이터를 학습용과 테스트용으로 나누는 함수  
StandardScaler: 데이터 표준화(평균 0, 표준편차 1로 변환) / LabelEncoder: 범주형 데이터를 숫자로 변환  
KNeighborsClassifier: K-최근접 이웃(KNN) 분류 알고리즘을 제공하는 머신러닝 모델  
seaborn: 고급 통계 시각화 도구, matplotlib 기반으로 다양한 통계적 그래프를 쉽게 생성

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns

In [28]:

df = pd.read_csv("C:/AI_File/car_evaluation.csv", header = None)
df

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [30]:
df.columns=['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety',
       'output']
df

      price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [31]:
df.columns

Index(['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety',
       'output'],
      dtype='object')

In [32]:
# 결측치 확인
print("\n 결측값 확인:")
print(df.isnull().sum())

 결측값 확인:
price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [33]:
columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety','output']

label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])


df

      price  maint  doors  persons  lug_capacity  safety  output
0         3      3      0        0             2       1       2
1         3      3      0        0             2       2       2
2         3      3      0        0             2       0       2
3         3      3      0        0             1       1       2
4         3      3      0        0             1       2       2
...     ...    ...    ...      ...           ...     ...     ...
1723      1      1      3        2             1       2       1
1724      1      1      3        2             1       0       3
1725      1      1      3        2             0       1       2
1726      1      1      3        2             0       2       1
1727      1      1      3        2             0       0       3

[1728 rows x 7 columns]

In [34]:
df['output'].value_counts()

2    1210
0     384
1      69
3      65
Name: output, dtype: int64

In [35]:
df.drop(columns=[], inplace=True)
# 컬럼 제거
df

      price  maint  doors  persons  lug_capacity  safety  output
0         3      3      0        0             2       1       2
1         3      3      0        0             2       2       2
2         3      3      0        0             2       0       2
3         3      3      0        0             1       1       2
4         3      3      0        0             1       2       2
...     ...    ...    ...      ...           ...     ...     ...
1723      1      1      3        2             1       2       1
1724      1      1      3        2             1       0       3
1725      1      1      3        2             0       1       2
1726      1      1      3        2             0       2       1
1727      1      1      3        2             0       0       3

[1728 rows x 7 columns]

In [9]:
X = df.drop('output', axis=1).values
y = df['output'].values

```
X = df.drop('output', axis=1).values
```
1. df에서 'output' 컬럼을 제외한 나머지 컬럼들만 가져와서 X에 저장.  
2. 즉, 입력 데이터(특징 값) 만 추출하는 것.
3. .values를 붙여서 데이터프레임(df) 을 넘파이 배열로 변환.    

 
- axis(방향을 뜻하는 옵션)

  -axis=0 : 행(row) 기준  
  -axis=1 : 열(column) 기준

---
```
y = df['output'].values
```
1. df에서 'output' 컬럼만 선택해서 y에 저장. 
2. 목표 값(라벨, 정답 데이터) 만 추출하는 것.

In [10]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [11]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [12]:
# 데이터 분할 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

X_train: 학습용 특징 데이터  
X_test: 테스트용 특징 데이터  
y_train: 학습용 라벨(정답)  
y_test: 테스트용 라벨(정답)

In [ ]:
# 표준화 (Scaling)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [15]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

print("\nDecision Tree Model")
print(f"Accuracy: {accuracy_score(y_test, dt_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, dt_pred))
print("- Confusion Matrix -")
print (confusion_matrix(y_test, dt_pred))

Decision Tree Model
Accuracy: 0.9769
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.92      0.95        79
           1       0.81      1.00      0.89        17
           2       0.99      1.00      0.99       240
           3       1.00      0.90      0.95        10

    accuracy                           0.98       346
   macro avg       0.94      0.95      0.95       346
weighted avg       0.98      0.98      0.98       346

- Confusion Matrix -
[[ 73   4   2   0]
 [  0  17   0   0]
 [  1   0 239   0]
 [  1   0   0   9]]

In [16]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("\nRandom Forest Model")
print(f"Accuracy: {accuracy_score(y_test, rf_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, rf_pred))
print("- Confusion Matrix -")
print (confusion_matrix(y_test, rf_pred))

Random Forest Model
Accuracy: 0.9711
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.95      0.94        79
           1       0.88      0.82      0.85        17
           2       1.00      0.99      0.99       240
           3       0.82      0.90      0.86        10

    accuracy                           0.97       346
   macro avg       0.91      0.92      0.91       346
weighted avg       0.97      0.97      0.97       346

- Confusion Matrix -
[[ 75   2   1   1]
 [  2  14   0   1]
 [  2   0 238   0]
 [  1   0   0   9]]

In [17]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)

print("\nSupport Vector Machine Model")
print(f"Accuracy: {accuracy_score(y_test, svm_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, svm_pred))
print("- Confusion Matrix -")
print (confusion_matrix(y_test, svm_pred))

Support Vector Machine Model
Accuracy: 0.9191
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.95      0.85        79
           1       1.00      0.47      0.64        17
           2       0.99      0.95      0.97       240
           3       0.70      0.70      0.70        10

    accuracy                           0.92       346
   macro avg       0.87      0.77      0.79       346
weighted avg       0.93      0.92      0.92       346

- Confusion Matrix -
[[ 75   0   3   1]
 [  7   8   0   2]
 [ 12   0 228   0]
 [  3   0   0   7]]

In [18]:
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

print("\nLogistic Regression Model")
print(f"Accuracy: {accuracy_score(y_test, lr_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, lr_pred))
print("- Confusion Matrix -")
print (confusion_matrix(y_test, lr_pred))

Logistic Regression Model
Accuracy: 0.6503
Classification Report:
              precision    recall  f1-score   support

           0       0.26      0.11      0.16        79
           1       0.00      0.00      0.00        17
           2       0.71      0.89      0.79       240
           3       0.22      0.20      0.21        10

    accuracy                           0.65       346
   macro avg       0.30      0.30      0.29       346
weighted avg       0.56      0.65      0.59       346

- Confusion Matrix -
[[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]

C:\Users\nikki\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nikki\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nikki\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [19]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)

print("\nK-Nearest Neighbors Model")
print(f"Accuracy: {accuracy_score(y_test, knn_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, knn_pred))
print("- Confusion Matrix -")
print (confusion_matrix(y_test, knn_pred))

K-Nearest Neighbors Model
Accuracy: 0.9422
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.89      0.47      0.62        17
           2       0.98      0.99      0.98       240
           3       1.00      0.90      0.95        10

    accuracy                           0.94       346
   macro avg       0.93      0.82      0.86       346
weighted avg       0.94      0.94      0.94       346

- Confusion Matrix -
[[ 72   1   6   0]
 [  9   8   0   0]
 [  3   0 237   0]
 [  1   0   0   9]]

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [21]:
model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test))

평균제곱근오차 0.7203242208101363

In [22]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 0.16184971098265896

In [23]:
model = RandomForestRegressor()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test))

평균제곱근오차 0.06041473988439307

In [24]:
model = SVR(kernel='linear')
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test))

평균제곱근오차 0.9057866400428652